# Generated by Django 6.0.3 on 2026-04-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habitlog_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habit',
            name='grace_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='last_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
