# Generated by Django 6.0.3 on 2026-04-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_current_streak_habit_grace_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='grace_count',
            field=models.IntegerField(default=0),
        ),
    ]
